name: Print Date and Time on Push

on:
  push:
    branches:
      - main

jobs:
  print-date-time:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Print Date and Time
        run: |
          echo "Current Date and Time: $(date)"
