name: Scheduled Print Date and Time

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour

jobs:
  scheduled-print:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Print Date and Time
        run: |
          echo "Current Date and Time: $(date)"
